// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('angularTree', []);

  angular.module('angularTree').directive('angularTree', function() {
    return {
      restrict: 'A',
      controller: function($scope) {
        $scope.$on('dragstart', function(e, children, index) {
          $scope.from = {
            children: children,
            index: index
          };
          return e.stopPropagation();
        });
        $scope.$on('dragover', function(e, children, index) {
          $scope.to = {
            children: children,
            index: index
          };
          return e.stopPropagation();
        });
        $scope.$on('dragleave', function(e) {
          $scope.to = void 0;
          return e.stopPropagation();
        });
        return $scope.$on('drop', function(e, direction) {
          $scope.$apply(function() {
            var draggable;
            if ($scope.from.children[$scope.from.index].children !== $scope.to.children) {
              draggable = $scope.from.children.splice($scope.from.index, 1)[0];
              return $scope.to.children.splice($scope.to.index, 0, draggable);
            }
          });
          return e.stopPropagation();
        });
      },
      compile: function(element) {
        var link, template;
        template = element.clone()[0].outerHTML;
        return link = function(scope) {
          return scope.template = template;
        };
      }
    };
  });

  angular.module('angularTree').directive('draggable', function($compile, mousePosition) {
    return {
      restrict: 'A',
      link: function(scope, element) {
        var parent;
        scope.children = scope.child.children;
        scope.$watchCollection('children', function(children) {
          var template;
          if (!(children != null ? children.length : void 0)) {
            return;
          }
          template = angular.element(scope.template);
          $compile(template)(scope);
          return element.append(template);
        });
        parent = scope.$parent;
        element.on('dragstart', function(e) {
          scope.$emit('dragstart', parent.children, parent.children.indexOf(scope.child));
          element.addClass('dragging');
          return e.stopPropagation();
        });
        element.bind('dragover', function(e) {
          scope.$emit('dragover', parent.children, parent.children.indexOf(scope.child));
          e.preventDefault();
          return e.stopPropagation();
        });
        return element.on('drop', function(e) {
          scope.$emit('drop');
          element.removeClass('dragging');
          return e.stopPropagation();
        });
      }
    };
  });

  angular.module('angularTree').service('mousePosition', function($window) {
    var clientX, clientY, _ref;
    _ref = [0, 0], clientX = _ref[0], clientY = _ref[1];
    angular.element($window).bind('mousemove', function(e) {
      var _ref1;
      return _ref1 = [e.clientX, e.clientY], clientX = _ref1[0], clientY = _ref1[1], _ref1;
    });
    return {
      getRelativeLeft: function(element) {
        if (element == null) {
          element = $window.document.body;
        }
        element = angular.element(element);
        if ((element[0].offsetLeft < clientX && clientX < element[0].offsetLeft + element[0].offsetWidth)) {
          return clientX - element[0].offsetLeft;
        }
      },
      getRelativeLeftPercent: function(element) {
        var relativeLeft;
        if (element == null) {
          element = $window.document.body;
        }
        element = angular.element(element);
        relativeLeft = this.getRelativeLeft(element);
        return relativeLeft && Math.round(relativeLeft / element[0].offsetWidth * 100);
      },
      getRelativeTop: function(element) {
        if (element == null) {
          element = $window.document.body;
        }
        element = angular.element(element);
        if ((element[0].offsetTop < clientY && clientY < element[0].offsetTop + element[0].offsetHeight)) {
          return clientY - element[0].offsetTop;
        }
      },
      getRelativeTopPercent: function(element) {
        var relativeTop;
        if (element == null) {
          element = $window.document.body;
        }
        element = angular.element(element);
        relativeTop = this.getRelativeTop(element);
        return relativeTop && Math.round(relativeTop / element[0].offsetHeight * 100);
      }
    };
  });

}).call(this);
